### ISSUE TITLE
Text Too Small in Login/Register Component

### ISSUE THREAD

**Issue by Olyve** [sgalizia/SandPiper#16]
The text is too small and kind of hard to read. Let's increase the padding and the text size to match the label.

<img width="497" alt="screen shot 2018-03-30 at 12 23 00 pm" src="https://user-images.githubusercontent.com/1574010/38150701-22e5287e-3415-11e8-9d48-5127397fce02.png">

**Comment by pomfy113** [comment]
Done. Changed both to 16px, takes more room in the input.
